{{- $name := printf "%s-audit-replica" (include "open-eidas.fullname" .) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  labels:
    {{- include "open-eidas.componentLabels" (dict "context" . "component" "audit-replica") | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.auditReplica.persistence.storageClassName }}
  storageClassName: {{ .Values.auditReplica.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.auditReplica.persistence.size }}
