{{- $name := printf "%s-audit-replica" (include "open-eidas.fullname" .) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "open-eidas.componentLabels" (dict "context" . "component" "audit-replica") | nindent 4 }}
spec:
  selector:
    {{- include "open-eidas.componentSelectorLabels" (dict "context" . "component" "audit-replica") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
