{{- $name := printf "%s-ca" (include "open-eidas.fullname" .) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-softhsm
  labels:
    {{- include "open-eidas.componentLabels" (dict "context" . "component" "ca") | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.ca.persistence.softhsm.storageClassName }}
  storageClassName: {{ .Values.ca.persistence.softhsm.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ca.persistence.softhsm.size }}
